name: pages
on:
  push

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: install
        working-directory: ./howmuch-client
        run: |
          npm install

      - name: git clone
        working-directory: ./howmuch-client
        run: |
          mkdir dist
          cd dist
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone -n -b gh-pages ${{ github.repositoryUrl }}

      - name: build
        working-directory: ./howmuch-client
        run: |
          npm run build

      - name: git push
        working-directory: ./howmuch-client/dist
        run: |
          git add -f .
          git commit -m "Publish dist"
          git push --force -u origin gh-pages
