name: pages
on:
  push

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: install
        working-directory: ./howmuch-client
        run: |
          npm install

      - name: build
        working-directory: ./howmuch-client
        run: |
          npm run build

      - name: git push
        working-directory: ./howmuch-client/dist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --global user.password ${{ github.token }}
          echo "step 1"
          git init
          git status
          echo "step 1"
          git commit -m "Publish dist"
          git status
          echo "step 2"
          git add .
          git status
          echo "step 3"
          git commit -m "Publish dist"
          git status
          echo "step 4"
          git push --force ${{ github.repositoryUrl }} gh-pages
          echo "step 5"
