name: pages
on:
  push

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: install
        working-directory: ./howmuch-client
        run: |
          npm install

      - name: build
        working-directory: ./howmuch-client
        run: |
          npm run build

      - name: git push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f howmuch-client/dist
          git commit -m "Publish dist"
          git subtree push --force --prefix howmuch-client/dist origin gh-pages
