name: pages
on:
  push

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: install
        working-directory: ./howmuch-client
        run: |
          npm install

      - name: build
        working-directory: ./howmuch-client
        run: |
          npm run build

      - name: git push
        working-directory: ./howmuch-client/dist
        run: |
          git config --global user.email "<>"
          git config --global user.name "${{ github.actor }}"
          git init
          git add -A
          git commit -m 'Publish dist'
          git push -f https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git main:gh-pages
